[base]
dimension = 2
output_dir = "output"

[solver]
name = "function"

[algorithm]
name = "bayes"
seed = 12345
label_list = ["Te", "ne"]

[algorithm.param]
min_list = [50.0, 0.5]
max_list = [2000.0, 8.0]
num_list = [100, 50]

[algorithm.bayes]
random_max_num_probes = 20
bayes_max_num_probes = 80
score = "TS"
interval = 5
num_rand_basis = 5000

[runner]
[runner.log]
interval = 20
